### ISSUE TITLE
BarChart width property warns object type

### ISSUE THREAD

**Issue by AlexKutkanych** [planttheidea/react-billboardjs#14]
Hi,
I'm having a warning in the console, when I'm passing `width` property as an object instead of a number.
I'm writing  like this:
`const bar = {
    width: {
        ratio: 1,
    },
};` and it shows me the following in the console:

![image](https://user-images.githubusercontent.com/22956226/39523513-9194d56c-4e1e-11e8-909f-2a97e2ca3b2e.png)

I'm using the latest version (1.4.1).
Please help me with this issue.

**Comment by planttheidea** [comment]
Is this a valid value? If so I can update the prop types.

Either way it shouldn't impact you beyond noise, it's just a standard prop types warning.

**Comment by planttheidea** [comment]
Fixed with release of `1.4.2`

**Comment by AlexKutkanych** [comment]
Thank you! Works fine.
