### ISSUE TITLE
Question: Update Label Background

### ISSUE THREAD

**Issue by serres2** [planttheidea/react-billboardjs#17]
Is it possible to adjust the contents of a label outside of just adjusting the formatting?

An example would be including a background color or something of the sort to improve the label's readability.

<img width="926" alt="screen shot 2018-08-21 at 3 33 51 pm" src="https://user-images.githubusercontent.com/14003373/44427599-a263fe00-a557-11e8-8d71-b21c80dead86.png">

**Comment by planttheidea** [comment]
Apologies for the late reply on this, the notification must have been buried somewhere.

This is a question for the upstream library ([billboard.js](https://naver.github.io/billboard.js/)), as `react-billboardjs` simply implements the options available to that library as standard props via React component.
