### ISSUE TITLE
How to use each chart.options ? 

### ISSUE THREAD

**Issue by seungdols** [planttheidea/react-billboardjs#18]
Hello, I'm curious about this library. Thanks for making react version of billboardjs.

I tried to apply pie.options so, I don't apply option.

https://naver.github.io/billboard.js/release/latest/doc/Options.html#.pie

How to apply options to chart component? pie options add in data object and then, 
pass on the data object to billboard charts component? 

example) 

```js 

...

pie = {
   innerRadius: 20,
   padAngle: 0.2
}

render() { 
	return <BillboardChart data={this.chartData} size={this.SIZE} pie={this.pie} />
}
```
Pie props don't working, maybe I did mistake ... ?

**Comment by planttheidea** [comment]
As mentioned in [the README](https://github.com/planttheidea/react-billboardjs#props), all top-level properties for options are passable as props to the component. Therefore, to pass `pie` options, you would pass the `pie` prop:

```javascript
import BillboardChart from 'react-billboardjs';

const PIE_OPTIONS = {
  label: {
    threshold: 0.1,
    ratio: 0.5,
  },
  padAngle: 0.25,
};

export const MyComponent = ({json}) => {
  const data = {
    json,
    type: 'pie',
  };

  return (
    <BillboardChart
      data={data}
      pie={PIE_OPTIONS}
    />
  );
};
```

Rather than passing a giant options object, you pass each property of that options object as a prop.

**Comment by seungdols** [comment]
@planttheidea Thanks a lot!!! 

I try to your advice, so passed pie prop to bb. 

```js 
 PIE_OPTIONS = {   
    innerRadius: 20,
  }

  render() {
    return <BillboardChart data={this.chartData} size={this.SIZE} pie={this.PIE_OPTIONS} />
  }
```

but, this case is don't work. 

```js 
pie = {
   innerRadius: 20,
}

render() { 
	return <BillboardChart data={this.chartData} size={this.SIZE} pie={this.pie} />
}
```

What difference between first case and second case ?

**Comment by planttheidea** [comment]
I mean it looks fine, but you've provided an incomplete representation.

If you look at the examples section in the repo, you'll see one for a donut chart. If you just change the word `donut` to `pie` you skills have an example you can play with.

**Comment by seungdols** [comment]
@planttheidea Umm, I'm sorry I missed out the information too much.

I try to apply options of Pie chart but doesn't work.

I did what I advised and it worked normally. 

Perhaps it was my mistake. 

Thank you.
