### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by miriyalee** [planttheidea/react-billboardjs#21]
Hi, how can I use this library with minified js?

Original project owner said 

`import bb from "billboard.js/dist/billboard.min.js";`

can include minified version.

https://github.com/naver/billboard.js/issues/696

**Comment by planttheidea** [comment]
`billboard.js` is an external dependency in the `dist` builds, so you should do the same when importing this library.

```javascript
import bb from 'billboard.js/dist/billboard.min.js';
import BillboardChart from 'react-billboardjs/dist/react-billboardjs.min.js';
```
