### ISSUE TITLE
Gauge chart data is not updated

### ISSUE THREAD

**Issue by renakim** [planttheidea/react-billboardjs#25]
Hi, I'm using a gauge chart in the react project.

I'm using the following settings, and when load new data using 'loadData' of chartInstance, the graph is updated but the text is not updated like below picture.

![image](https://user-images.githubusercontent.com/29771876/55043715-c56d0800-507a-11e9-90ae-17120226ba4c.png)

```
<BillboardChart
  // isPure
  // unloadBeforeLoad
  data={{
    columns: [],
    type: "gauge"
  }}
  gauge={{
    label: {
      format: function(value, ratio) {
        return value;
      }
    },
    min: Number(settings.min),
    max: Number(settings.max),
    units: settings.units
  }}
  size={size}
  color={color}
  ref={instance => setChartInstance(instance)}
/>
```
```
chartInstance.loadData({
  columns: [[label, value]]
});
```

Please check this. 
Thank you.

**Comment by planttheidea** [comment]
Internally, `chartInstance.loadData` is just a pass-through to the native [chart.load](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load) method with the data you passed, there is no transformation of the data. Does this work as expected just using billboard.js?

**Comment by renakim** [comment]
I didn't use billboard.js directly, but the result was same when using `chartInstance.chart.load()`.
Then I'll add this issue to billboard.js.

**Comment by planttheidea** [comment]
Cool, sounds good, I'll close this as it sounds like an upstream issue. If it turns out this is specific to this library, feel free to reopen.
