### ISSUE TITLE
Filtering data does not reposition labels

### ISSUE THREAD

**Issue by teo-stanescu** [planttheidea/react-billboardjs#36]
Hi!
I'm working on a relatively large project which is using this library for visualizing data.
We've created a custom chart, which I have isolated in a component in the following sandbox:

https://codesandbox.io/embed/simple-billboardjs-line-chart-oflsl?fontsize=14&hidenavigation=1&theme=dark

The main issue is that when clicking on one of the items in the legend to show/hide it from the chart, the according label disappears, but the other one remain in their initial position. Forcing the data to reload solves the issue (i.e. actions like opening the Chrome console).

**Comment by planttheidea** [comment]
This sounds like an upstream request, there isn't anything in this code that handles this kind of behavior. I would recommend filing an issue with `billboard.js` itself. At minimum they can offer configuration parameters to accomplish what you are looking for.

**Comment by planttheidea** [comment]
Closed due to inactivity.
