### ISSUE TITLE
Problems with import "react-billboardjs/lib/billboard.css";

### ISSUE THREAD

**Issue by keiwanmosaddegh** [planttheidea/react-billboardjs#39]
Hi,

I don't believe this is something that'd be considered a "real" issue, but rather something I'm strugglng with. I've been trying to make my React Component read and apply the data of the .css file but without any luck. I'm aware that this way of importing billboard.css is for Webpack, and I know that we're using Webpack in our project. However, the webpack configs are quite complex, and I'd prefer not changing anything there.

Do you mind sharing any other method of importing the css to the component?

Thanks! :)

**Comment by planttheidea** [comment]
I know that for those unfamiliar with Webpack the configuration can be the most intimidating. Unfortunately, the simplest and easiest way to accomplish this is to make changes to the Webpack config to apply the `css-loader` + `style-loader`. There are other ways to accomplish this, but they are much (_much_) more challenging ... it's kind of like asking if there are any other methods of stopping a moving car other than pressing the brakes. :)

Fortunately, the changes necessary to the Webpack config to make this work are quite simple. Webpack has improved their documentation tremendously over the last couple of years, and the directions in the [`Getting Started` section for the `css-loader`](https://webpack.js.org/loaders/css-loader/#getting-started) should be all you need to do.

Good luck!

**Comment by keiwanmosaddegh** [comment]
Thank you so much for taking your time to answer. I've made a rather ugly fix for now. I copied the .css file from the node module, and wrapped all the containing css with :global {...}. This made the css accessible globally, as if it'd be rightly configured through Webpack config.

I'll definitely look into creating a more long term solution, thank you for your advice! :)
