### ISSUE TITLE
Replace 'componentWillUpdate' to stop React 17 warning about it

### ISSUE THREAD

**Issue by junhyuk-prestolabs** [planttheidea/react-billboardjs#40]
https://github.com/planttheidea/react-billboardjs/issues/34

Hi, looks like it is not working with 17.0.0-rc.0

```js
const COMPONENT_WILL_UPDATE_NAME =
  MAJOR_VERSION >= 16 && MINOR_VERSION >= 3 ? 'UNSAFE_componentWillUpdate' : 'componentWillUpdate';
```

imho, should be changed to

```js
const COMPONENT_WILL_UPDATE_NAME =
  (MAJOR_VERSION >= 16 && MINOR_VERSION >= 3) || MAJOR_VERSION >= 17 ? 'UNSAFE_componentWillUpdate' : 'componentWillUpdate';
```

thanks.

**Comment by junhyuk-prestolabs** [comment]
![image](https://user-images.githubusercontent.com/58673794/90015748-fd163780-dce3-11ea-840e-6b4f2c4f3ff6.png)

Updated with my method, 

React.StrictMode shows this danger log.

Maybe we can think about convert to hooks.

**Comment by planttheidea** [comment]
Appreciate the notice, I can try to tackle this over the next week. The change should be trivial, its just about finding time.

I'll be going the middle ground of replacing use of `UNSAFE_componentWillUpdate` for more recent versions of React with `getSnapshotBeforeUpdate`. It will not provide the same error in strict mode, and will not be a breaking change as hooks would be.
