### ISSUE TITLE
Billboard 2 Plans

### ISSUE THREAD

**Issue by jwarchol** [planttheidea/react-billboardjs#43]
What are the plans for the upgrade to Billboard 2.0 and later? Has anyone tried it out yet?

**Comment by planttheidea** [comment]
Based on what I'm seeing in [the changeling to v2](https://github.com/naver/billboard.js/blob/master/CHANGELOG-v2.md), it should just work with it. The abstraction layer is pretty low.

We may be able to get away to updating dependences and calling it a day. If you're willing to make a PR, always welcome. 😁

**Comment by planttheidea** [comment]
I have just released a beta for version 2 support. If you want to try it out yourself, you can install via:

```bash
npm install react-billboardjs@next
```

I'll let the beta stew for a while, as there are breaking changes, but should hopefully get us to latest.
