### ISSUE TITLE
React warning related to getSnapshotBeforeUpdate()

### ISSUE THREAD

**Issue by jwarchol** [planttheidea/react-billboardjs#44]
I'm getting up to speed on this library and in my small test app I'm seeing this warning:

> Warning: BillboardChart: getSnapshotBeforeUpdate() should be used with componentDidUpdate(). This component defines getSnapshotBeforeUpdate() only.

I see a couple of recent issues and PRs related to this area of the lib and I'm not sure if there is something I'm missing or not. Should BillboardChart be implementing componentDidUpdate?

```
├─ react-billboardjs@1.5.5
└─ react@16.13.1
```

**Comment by jwarchol** [comment]
Also seeing this:

> BillboardChart.getSnapshotBeforeUpdate(): A snapshot value (or null) must be returned. You have returned undefined.

**Comment by planttheidea** [comment]
They may have added in warnings to guide developers, but there should be no runtime impact, just console noise in development.

If I get some time I'll see if I can refactor things to eliminate the noise.

**Comment by planttheidea** [comment]
Should be resolved with `1.5.6`.
