### ISSUE TITLE
Cannot resolve dependency 'react-billboardjs/dist/billboard.css'

### ISSUE THREAD

**Issue by zwagner86** [planttheidea/react-billboardjs#48]
Hello,

Using `react-billboardjs@next` and there don't appear to be any css files in the module's `dist` folder.

Here's a screenshot of what I see there:
![Screen Shot 2021-02-25 at 11 57 58 AM](https://user-images.githubusercontent.com/4967196/109195981-c45e1d00-7760-11eb-9672-006270ae3907.png)

**Comment by planttheidea** [comment]
One of the changes is that CSS files are no longer redistributed with the package. Please import the CSS files from `billboard.js` itself.
