### ISSUE TITLE
Using unloadBeforeLoad=false does not work as intended

### ISSUE THREAD

**Issue by miguelCT** [planttheidea/react-billboardjs#5]
Hi again,

I've been using the new vewsion *1.2.0* since the release, but I think my last PR introduced a bug that prevents the chart to work as inteded when the *unloadBeforeLoad* is not set.

When I applied the changes to solve the bug related to the issue #2  I just thought that the *unload* option in *loadData* function would accept Boolean (true/false), Array or String as value, but there's an exception. 

Apparently, the *unload* option does not accept *"false"* as value so, if it's set to that value, this option will work as it would be set to *"true"* (in my tests at least ). Therefore, with the current code, the old data will always be unloaded before the new data.

So this part: 
```js
 instance.loadData({
      ...data,
      unload: unloadBeforeLoad
    });
```
should be changed to:
```js
instance.loadData(unloadBeforeLoad ? {...data, unload: true} : data);
```

I made the assuption that *"false"* was an accepted value based on the API description but I was wrong. I'm sorry about the bug. 
I'll submit a new PR to fix it.

**Comment by planttheidea** [comment]
That is a totally reasonable assumption ... I think this may actually be a bug upstream with billboard itself. I'm happy to merge this PR later today but you may consider filing a ticket upstream.

**Comment by miguelCT** [comment]
You're right. I think I'll open an issue to them, at least to ask if that is working as intended.

Wait then until I get a response from Billboardjs and see if this PR applies or not.

**Comment by miguelCT** [comment]
I've just submitted a new issue in Billboardjs to ask about this https://github.com/naver/billboard.js/issues/321.

**Comment by planttheidea** [comment]
@miguelCT because they just kind of dismissed your issue and closed it (while it is still valid), I went ahead and [created a PR to "enhance" it](https://github.com/naver/billboard.js/pull/333) (since it is apparently not a "fix"). Until that is merged in I have incorporated your changes into the new release to align with `1.3.0`, so this should no longer be an issue.
