### ISSUE TITLE
Fix billboard.css path in README

### ISSUE THREAD

**Issue by ghyoo91** [planttheidea/react-billboardjs#53]
Hi.

As you mentioned in CHANGELOG, since 2.0.0 there was no billboard.css file in the "react-billboardjs/dist/".

The thing is, the usage in the README is still saying: import 'react-billboardjs/dist/billboard.css';
So I confused by error that says there is no such file on the path before I read CHANGELOG, and I should import it directly from "billboard.js/dist/billboard.css".
![image](https://user-images.githubusercontent.com/20279300/114665654-423dae00-9d38-11eb-902a-e7dd07ba8afb.png)

Maybe we should fix the path in README to 'billboard.js/dist/billboard.css' or some guideline with comment to stop making people like me(or  #48 )

Thanks for your efforts to create this project. It was really helpful to me.

**Comment by planttheidea** [comment]
:facepalm: Well that is a miss! README has been updated with correct usage. I'll also go back and fix the README for v2. Thanks for pointing this out!
