### ISSUE TITLE
data.label does not accept format other than function or bool

### ISSUE THREAD

**Issue by daisy12321** [planttheidea/react-billboardjs#72]
I am passing in data where the labels have different formats for each series:
```
    labels: {
      format: {
        A: function(x) { return d3.format(".3%")(x + 0.90); },
        B: function(x) { return d3.format(".3%")(x); },
      }
    }
```

This worked properly in billboard.js, but when I use react-billboardjs, the browser console shows the warning:
```
Warning: Failed prop type: Invalid prop `data.labels` supplied to `BillboardChart`, expected one of type [boolean, function].
```

I believe the solution is to expand this:
https://github.com/planttheidea/react-billboardjs/blob/master/src/propTypes.js#L289-L298

**Comment by planttheidea** [comment]
You are correct. For this, I believe the type would need to be expanded to:

```js
format: oneOfType([func, objectOf(func)]),
```

I'm a little busy at the moment, because we just had our second child, but if you wanted to do a PR I'm happy to approve and publish at the next opportunity.
