### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by cesarvarela** [planttheidea/react-billboardjs#81]
This seems to work properly with the latest React, so it will be a matter of just updating peer deps?

**Comment by planttheidea** [comment]
Yes, should be all that is necessary if it is working properly. If you want to set up a PR thar would be most appreciated, otherwise I can try to get to it in the next few days when I have some time.

**Comment by planttheidea** [comment]
Apologies for the delay, but finally got around to taking care of this; it should be handled as-of `3.0.3`. If there are further issues, please let me know!
