### ISSUE TITLE
Tooltip.order doesn't allow empty strings

### ISSUE THREAD

**Issue by AlexKott** [planttheidea/react-billboardjs#9]
The [documentation](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) for tooltips suggests using an empty string for data bound order:

>If want to order as data bound, set any value rather than asc, desc or null. (ex. empty string "")

However, The PropTypes of `ORDER_SHAPE` are currently restricted to `func`, `'asc'`, `'desc'` or `null`. Naturally, if you try the empty string, you'll get `Failed prop type: Invalid prop 'tooltip.order' supplied to 'BillboardChart'`. I suggest adding the empty string to the PropTypes validation in shapes.js.

I can create a PR for this if you agree.

**Comment by planttheidea** [comment]
@AlexKott Good callout! Yes please if you can submit a PR, that would great.

Based on the documentation, it seems that the propType could be extremely open-ended ... what do you think would reasonable? Just allowing any string value? Or reading the documentation literally and allowing truly any value? Cuz if we're reading this to the letter, `PropTypes.any` would be correct, but I always feel lazy with those declarations.

**Comment by AlexKott** [comment]
@planttheidea I also think that `PropTypes.any` isn't a good solution. Since the docs propose using the empty string adding `''` would be sufficient. People can always refrence to this issue if they're having the same problem.

**Comment by planttheidea** [comment]
Fair enough, adding the empty string explicitly is sufficient to allow the functionality missing currently. I'm sold.

**Comment by planttheidea** [comment]
Your fix was included in the `1.4.0` release. Thanks!
